# Generated by Django 2.2.16 on 2020-10-24 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(max_length=1500, verbose_name='متن پیام'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='users/%Y/%m/%d', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('waiting', 'در انتظار'), ('published', 'منتشر شده')], default='waiting', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='posttranslation',
            name='title',
            field=models.CharField(max_length=250, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='tagstranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='عنوان'),
        ),
    ]
