# Generated by Django 2.2.16 on 2020-09-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomtag',
            name='content_object',
        ),
    ]
