# Generated by Django 2.2.16 on 2020-10-18 08:50

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producttranslation',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
    ]
