# Generated by Django 2.2.16 on 2020-10-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20201018_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='producttranslation',
            managers=[
            ],
        ),
    ]
