# Generated by Django 2.2.16 on 2020-09-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200920_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visit_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
