# Generated by Django 2.2.16 on 2020-10-27 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_bookmarkproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkproduct',
            options={'ordering': ('-created',), 'verbose_name': 'لیست علاقه مندی ها', 'verbose_name_plural': 'لیست علاقه مندی ها'},
        ),
        migrations.AddField(
            model_name='bookmarkproduct',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
