# Generated by Django 2.2.16 on 2020-10-27 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20201027_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product', verbose_name='products'),
        ),
        migrations.AlterField(
            model_name='bookmarkproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
