# Generated by Django 2.2.16 on 2020-10-27 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20201027_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmarkproduct',
            options={'verbose_name': 'لیست علاقه مندی ها', 'verbose_name_plural': 'لیست علاقه مندی ها'},
        ),
        migrations.AlterField(
            model_name='bookmarkproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='bookmarkproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
